import type { Project } from './types';
import { Project as ProjectSchema } from './types';

/** Generate a sane default project so the app has something to show on first launch. */
export function defaultProject(): Project {
  const now = new Date().toISOString();
  const proj: Project = {
    meta: {
      name: 'Untitled aircraft',
      author: '',
      units: 'metric',
      createdAt: now,
      updatedAt: now,
      appVersion: '0.1.0',
    },
    aircraft: {
      wing: {
        span_mm: 1200,
        root_chord_mm: 220,
        tip_chord_mm: 180,
        sweep_deg: 0,
        dihedral_deg: 3,
        incidence_deg: 2,
        root_le_x_mm: 230,
      },
      htail: {
        span_mm: 420,
        root_chord_mm: 130,
        tip_chord_mm: 90,
        root_le_x_mm: 740,
      },
      vtail: {
        height_mm: 160,
        root_chord_mm: 150,
        tip_chord_mm: 80,
        root_le_x_mm: 760,
      },
      fuselage: {
        length_mm: 900,
        max_width_mm: 80,
        max_height_mm: 110,
      },
      batteryBay: { x_min_mm: 70, x_max_mm: 220, z_mm: 0 },
    },
    materials: [
      { id: 'mat-foam5', name: 'Adams readi-board 5 mm', kind: 'sheet', density: 230, thickness_mm: 5 },
      { id: 'mat-foam-light', name: 'Depron 6 mm', kind: 'sheet', density: 60, thickness_mm: 6 },
      { id: 'mat-spar-cf4', name: 'Carbon rod ⌀4 mm', kind: 'linear', density: 18 },
      { id: 'mat-glue-hot', name: 'Hot-glue bead', kind: 'linear', density: 3 },
      { id: 'mat-tape', name: 'Packing tape', kind: 'linear', density: 2 },
      { id: 'mat-pla', name: 'PLA print', kind: 'volume', density: 1.24 },
    ],
    parts: [
      { id: 'p-motor', name: '2212 1000kV motor', category: 'motor', mass_g: 55 },
      { id: 'p-esc', name: '30 A ESC', category: 'esc', mass_g: 28 },
      { id: 'p-batt', name: '3S 2200 mAh LiPo', category: 'battery', mass_g: 185 },
      { id: 'p-rx', name: 'FrSky R-XSR', category: 'receiver', mass_g: 6 },
      { id: 'p-servo', name: '9 g servo', category: 'servo', mass_g: 9 },
    ],
    components: [
      {
        id: 'c-motor',
        name: 'Motor',
        kind: 'motor',
        source: { kind: 'part', partId: 'p-motor', count: 1 },
        x_mm: 0,
        y_mm: 0,
        z_mm: 0,
        visible: true,
      },
      {
        id: 'c-esc',
        name: 'ESC',
        kind: 'esc',
        source: { kind: 'part', partId: 'p-esc', count: 1 },
        x_mm: 40,
        y_mm: 0,
        z_mm: 0,
        visible: true,
        movable: { x: true, xRange_mm: [30, 80] },
      },
      {
        id: 'c-batt',
        name: 'Battery',
        kind: 'battery',
        source: { kind: 'part', partId: 'p-batt', count: 1 },
        x_mm: 140,
        y_mm: 0,
        z_mm: 0,
        visible: true,
        movable: { x: true, xRange_mm: [70, 220] },
      },
      {
        id: 'c-rx',
        name: 'Receiver',
        kind: 'receiver',
        source: { kind: 'part', partId: 'p-rx', count: 1 },
        x_mm: 280,
        y_mm: 0,
        z_mm: 0,
        visible: true,
      },
      {
        id: 'c-servo-elev',
        name: 'Elevator servo',
        kind: 'servo',
        source: { kind: 'part', partId: 'p-servo', count: 1 },
        x_mm: 700,
        y_mm: 0,
        z_mm: 0,
        visible: true,
      },
      {
        id: 'c-servo-rud',
        name: 'Rudder servo',
        kind: 'servo',
        source: { kind: 'part', partId: 'p-servo', count: 1 },
        x_mm: 720,
        y_mm: 0,
        z_mm: 0,
        visible: true,
      },
      {
        id: 'c-wing-skin',
        name: 'Wing skin (foam)',
        kind: 'structure',
        source: {
          kind: 'sheet',
          materialId: 'mat-foam5',
          // approx area = span * mean chord, both sides
          area_mm2: 1200 * ((220 + 180) / 2),
        },
        x_mm: 320,
        y_mm: 0,
        z_mm: 0,
        visible: true,
      },
      {
        id: 'c-fus-sides',
        name: 'Fuselage sides',
        kind: 'structure',
        source: { kind: 'sheet', materialId: 'mat-foam5', area_mm2: 900 * 110 * 2 },
        x_mm: 450,
        y_mm: 0,
        z_mm: 0,
        visible: true,
      },
      {
        id: 'c-htail',
        name: 'Horizontal tail',
        kind: 'structure',
        source: { kind: 'sheet', materialId: 'mat-foam5', area_mm2: 420 * ((130 + 90) / 2) },
        x_mm: 790,
        y_mm: 0,
        z_mm: 0,
        visible: true,
      },
      {
        id: 'c-spar',
        name: 'Main spar (carbon rod)',
        kind: 'spar',
        source: { kind: 'linear', materialId: 'mat-spar-cf4', length_mm: 1100 },
        x_mm: 290,
        y_mm: 0,
        z_mm: 0,
        visible: true,
      },
      {
        id: 'c-glue',
        name: 'Hot-glue lines',
        kind: 'glue',
        source: { kind: 'linear', materialId: 'mat-glue-hot', length_mm: 3500 },
        x_mm: 450,
        y_mm: 0,
        z_mm: 0,
        visible: true,
      },
    ],
    sheets: [],
    aero: { cl_max: 1.2, air_density_kg_m3: 1.225, cruise_speed_m_s: 15 },
  };
  // Auto-derive a sensible default CG target at 30 % MAC.
  // (Computed lazily by UI when project loads; not stored on disk by default.)
  return ProjectSchema.parse(proj);
}
